// Exercises the view switch and the editor: node scripts/views.mjs <outDir>
import { chromium } from "playwright-core"
const out = process.argv[2]
const browser = await chromium.launch({ channel: "chrome" })
const page = await browser.newPage({ viewport: { width: 1280, height: 860 }, reducedMotion: "reduce" })
const errors = []
page.on("pageerror", (e) => errors.push(e.message))
page.on("console", (m) => m.type() === "error" && errors.push(m.text().slice(0, 200)))
await page.goto(`${process.env.SMD_URL ?? "http://localhost:3000"}/?sample=annual-report`, { waitUntil: "networkidle" })
await page.waitForSelector('.smd[data-ready="true"]', { timeout: 25000 })
const view = page.getByRole("radiogroup", { name: "View" })
console.log("switch precedes theme picker:", await page.evaluate(() => { const a = document.querySelector(".smd-view-switch"), b = document.querySelector('[aria-label="Choose theme"]'); return !!(a.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING) }))
console.log("initial:", await view.getByRole("radio", { checked: true }).getAttribute("aria-label"))
await view.getByRole("radio", { name: "Plain rendering" }).click()
await page.waitForTimeout(400)
console.log("plain: h1 =", JSON.stringify(await page.locator(".smd-plain h1").textContent()), "| tables:", await page.locator(".smd-plain table").count(), "| charts:", await page.locator(".smd-chart").count(), "| hero:", await page.locator(".smd-hero").count())
await page.screenshot({ path: `${out}/view-plain.png` })
await page.getByRole("button", { name: /^Open (contents|chat)$/ }).click()
await page.getByRole("link", { name: "Regional performance" }).click()
await page.waitForTimeout(1200)
console.log("contents work in plain view: heading at", await page.evaluate(() => Math.round(document.getElementById("regional-performance").getBoundingClientRect().top)), "px")
await page.keyboard.press("Escape")
await view.getByRole("radio", { name: "Plain rendering" }).focus()
await page.keyboard.press("ArrowLeft")
await page.waitForTimeout(400)
console.log("after ArrowLeft:", await view.getByRole("radio", { checked: true }).getAttribute("aria-label"), "| contents button shown:", await page.getByRole("button", { name: /^Open (contents|chat)$/ }).count())
const editor = page.getByRole("textbox", { name: "Edit markdown" })
const text = await editor.inputValue()
await editor.fill(text.replace("# 2024 in review: a year of disciplined growth", "# Edited in the browser").replace("| Other | 4% |", "| Other | 4% |\n\n## A brand new section\n\nAdded while editing."))
await page.evaluate(() => window.scrollTo(0, 0))
await page.screenshot({ path: `${out}/view-source.png` })
await view.getByRole("radio", { name: "Stunning" }).click()
await page.waitForTimeout(1500)
console.log("after edit → title:", JSON.stringify(await page.locator(".smd-display").textContent()), "| new section present:", await page.locator("#a-brand-new-section").count() === 1, "| view kept:", await view.getByRole("radio", { checked: true }).getAttribute("aria-label"))
await view.getByRole("radio", { name: "Markdown text" }).click()
console.log("editor keeps the edit:", (await page.getByRole("textbox", { name: "Edit markdown" }).inputValue()).startsWith("---") , (await page.getByRole("textbox", { name: "Edit markdown" }).inputValue()).includes("# Edited in the browser"))
console.log(errors.length ? errors.join("\n") : "no console errors")
await browser.close()
